### ISSUE TITLE
Error cloning Vertex with Edge to self - exception thrown attempting to remove same Edge twice

### ISSUE THREAD

**Issue by phyrwork** [graphp/graph#154] opened 2017-07-25 18:00 UTC
Attempting to createGraphCloneVertices where one or more Vertexes has an Edge to itself throws Fhaculty\Graph\Exception\InvalidArgumentException: Invalid Edge does not exist in this Graph

**Comment by clue** [comment] 2017-08-07 08:26
Thanks for reporting! It looks like this may be a duplicate of https://github.com/clue/graph/pull/149 which was fixed a while ago, but still didn't get a tagged release so far.

Also thanks for your other contributions the last weeks, I'll get to this as soon as possible! :+1:  Your contributions are very much appreciated and I've now put this higher on my todos so I'm planning to get back to this and update the whole "graphp" organization starting next week :shipit: 

Just reaching out, but I'm seeing some high quality PRs and input coming from you, so if you're interesting in helping out with maintaining this project, please drop me a line via email :heart:

**Closed by clue** 2017-08-07 08:26 UTC
Labels: bug
